### ISSUE TITLE
First save in a fresh Rails application fails

### ISSUE THREAD

**Issue by railsbros-dirk** [triAGENS/guacamole#101]
After creating a fresh Rails application saving a model will fail. After the `connection` object has been called the first time everything works as expected. This should be done by Guacamole itself.

```
>> u = User.new name: "Pinkie"; UsersCollection.save u
Ashikawa::Core::ResourceNotFound: Status 404: The Resource you requested was not found on the server
        from /Users/dbreuer/.rvm/gems/ruby-2.1.2/gems/ashikawa-core-0.13.1/lib/ashikawa-core/error_response.rb:100:in `resource_not_found'
        from /Users/dbreuer/.rvm/gems/ruby-2.1.2/gems/ashikawa-core-0.13.1/lib/ashikawa-core/error_response.rb:50:in `on_complete'
        from /Users/dbreuer/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:9:in `block in call'
        from /Users/dbreuer/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:57:in `on_complete'
        from /Users/dbreuer/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:8:in `call'
        from /Users/dbreuer/.rvm/gems/ruby-2.1.2/gems/ashikawa-core-0.13.1/lib/ashikawa-core/x_arango_version.rb:20:in `call'
        from /Users/dbreuer/.rvm/gems/ruby-2.1.2/gems/faraday_middleware-0.9.1/lib/faraday_middleware/request/encode_json.rb:23:in `call'
        from /Users/dbreuer/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'
        from /Users/dbreuer/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'
        from /Users/dbreuer/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday/connection.rb:177:in `post'
        from /Users/dbreuer/.rvm/gems/ruby-2.1.2/gems/ashikawa-core-0.13.1/lib/ashikawa-core/connection.rb:103:in `public_send'
        from /Users/dbreuer/.rvm/gems/ruby-2.1.2/gems/ashikawa-core-0.13.1/lib/ashikawa-core/connection.rb:103:in `send_request'
        from /Users/dbreuer/.rvm/gems/ruby-2.1.2/gems/ashikawa-core-0.13.1/lib/ashikawa-core/transaction.rb:94:in `execute'
        from /Users/dbreuer/.rvm/gems/ruby-2.1.2/gems/guacamole-0.4.0/lib/guacamole/transaction.rb:159:in `execute_transaction'
        from /Users/dbreuer/.rvm/gems/ruby-2.1.2/gems/guacamole-0.4.0/lib/guacamole/transaction.rb:95:in `run'
        from /Users/dbreuer/.rvm/gems/ruby-2.1.2/gems/guacamole-0.4.0/lib/guacamole/collection.rb:325:in `with_transaction'
... 15 levels...
        from /Users/dbreuer/.rvm/gems/ruby-2.1.2/gems/railties-4.1.7/lib/rails/commands/console.rb:9:in `start'
        from /Users/dbreuer/.rvm/gems/ruby-2.1.2/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:69:in `console'
        from /Users/dbreuer/.rvm/gems/ruby-2.1.2/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
        from /Users/dbreuer/.rvm/gems/ruby-2.1.2/gems/railties-4.1.7/lib/rails/commands.rb:17:in `<top (required)>'
        from /Users/dbreuer/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
        from /Users/dbreuer/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `block in require'
        from /Users/dbreuer/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /Users/dbreuer/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
        from /Users/dbreuer/Documents/Work/GalaxyCats/projects/ArangoDB/playground/ml-test-prj/bin/rails:8:in `<top (required)>'
        from /Users/dbreuer/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:241:in `load'
        from /Users/dbreuer/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:241:in `block in load'
        from /Users/dbreuer/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /Users/dbreuer/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:241:in `load'
        from /Users/dbreuer/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/dbreuer/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
   UsersCollection
=> UsersCollection
>> UsersCollection.connection
=> #<Ashikawa::Core::VertexCollection id="866601375037" name="users" content_type=:document database=#<Ashikawa::Core::Database host="localhost" port=8529 scheme="http">>
>> u = User.new name: "Pinkie"; UsersCollection.save u
=> #<User:0x000001015db568 @name="Pinkie", @key="866602685757", @rev="866602685757", @created_at=2014-12-19 14:31:36 +0100, @updated_at=2014-12-19 14:31:36 +0100, @validation_context=nil, @errors=#<ActiveModel::Errors:0x000001015d8c78 @base=#<User:0x000001015db568 ...>, @messages={}>>
```

**Comment by railsbros-dirk** [comment]
This has been fixed with #103 and specs have been added in #106.
